# Generated by Django 3.1 on 2020-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, verbose_name='полный текст статьи')),
                ('image', models.ImageField(blank=True, upload_to='article_images', verbose_name='ииллюстрация')),
                ('sort_description', models.TextField(blank=True, max_length=90, verbose_name='краткий текст статьи')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='категория активна')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['created'],
            },
        ),
    ]
