# Generated by Django 3.1 on 2020-08-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200827_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sort_description',
            field=models.TextField(blank=True, max_length=190, verbose_name='краткий текст статьи'),
        ),
    ]
