# Generated by Django 3.1 on 2020-08-28 09:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_article_sort_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='заголовок')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
