# Generated by Django 3.1 on 2020-08-28 22:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_newart'),
    ]

    operations = [
        migrations.AddField(
            model_name='newart',
            name='content2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
