# Generated by Django 3.1 on 2020-08-28 22:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_newart_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
